<div class="container">
	<div class="row">
		<div class="col-sm-6">
			<div class="contactinfo">
				<ul class="nav nav-pills">
					<li><a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
					<li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
				</ul>
			</div>
		</div>
		<div class="col-sm-6">
			<div class="social-icons pull-right">
				<ul class="nav navbar-nav">
					<li><a href="<?php echo $this->getData('store_facebook');?>"><i class="fab fa-facebook-f"></i></a></li>
					<li><a href="#"><i class="fab fa-twitter"></i></a></li>
					<li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
					<li><a href="#"><i class="fab fa-dribbble"></i></a></li>
					<li><a href="#"><i class="fab fa-google-plus-g"></i></a></li>
				</ul>
			</div>
		</div>
	</div>
</div>



